[package]
name = "corpus-queries-derive"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
corpus-queries-impl = { path = "../queries-impl" }
